### ISSUE TITLE
Include Hardware requirements for running Getting-Started (disk-space etc.)

### ISSUE THREAD

**Issue by kishorebhatia** [blockapps/strato-getting-started#10]

**Comment by kishorebhatia** [comment]
@nikitamendelbaum let's calculate the real disk-space consumed by the STRATO-GS images on a clean machine.
use "docker system df"

**Comment by kishorebhatia** [comment]
also put a min. requirement of say a 2-vcpu 8GB machine

**Comment by kjameslubin** [comment]
@kishorebhatia can you move this issue to our internal tracker and close?
