### ISSUE TITLE
The ./strato-run.sh command can't pull postgre

### ISSUE THREAD

**Issue by Robb-Greathouse** [blockapps/strato-getting-started#12]
Hi,

I followed the instructions on https://github.com/blockapps/strato-getting-started .  However, when I run ./strato-run.sh I get the following error as it tries to pull postgresql

Pulling postgres (registry-aws.blockapps.net:5000/blockapps-repo/silo-postgres:latest)...
latest: Pulling from blockapps-repo/silo-postgres
Digest: sha256:3302ca710f10a10dbd38067c395d933019fc6e63725bc4679d39ba55733f756f
Status: Image is up to date for registry-aws.blockapps.net:5000/blockapps-repo/silo-postgres:latest
Pulling postgres-cirrus (postgres:9.6)...
ERROR: Get https://registry-1.docker.io/v2/library/postgres/manifests/9.6: unauthorized: incorrect username or password

I am using the username and password you sent me via email.

**Comment by samrit** [comment]
@Robb-Greathouse Please visit http://developers.blockapps.net/install/local/ and signup for the trial. This will give you access to the images.

**Comment by kjameslubin** [comment]
@Robb-Greathouse were you able to pull the images?
