### ISSUE TITLE
Change units for Balance field

### ISSUE THREAD

**Issue by ArturoLR** [blockapps/strato-getting-started#15]
Hi! 

I'm using STRATO Management Dashboard and I need to change the units for the Balance field (actually the unit is a wei) and set this value = 0 when a new user is created.
This is possible?
How can I do it?

**Comment by martyall** [comment]
When you create a user, if you do not wish them to inherit the initial amount of either then set the `faucet` query parameter to false. See the `BlocApi` docs link (upper right hand corner of the dashboard) for more details.

You cannot currently change the unit of currency you would like to view your balance in.

**Comment by ArturoLR** [comment]
I have a last question. Exist another one version or Blockapps application that let me manage the units of this field?

**Comment by martyall** [comment]
Not currently, no.
