### ISSUE TITLE
Getting 500 Internal Server Error when compiling a valid contract via Bloc API

### ISSUE THREAD

**Issue by suchitgupta60** [blockapps/strato-getting-started#16]
curl -X POST "http://ec2-34-204-212-206.compute-1.amazonaws.com/bloc/v2.1/contracts/compile" -H  "accept: application/json;charset=utf-8" -H  "content-type: application/json;charset=utf-8" -d "[  {    \"contractName\": \"ERC20Interface\",    \"searchable\": [      \"ERC20Interface\"    ],    \"source\": \"contract ERC20Interface {      function totalSupply() constant returns (uint256 totalSupply);         function balanceOf(address _owner) constant returns (uint256 balance);         function transfer(address _to, uint256 _value) returns (bool success);         function transferFrom(address _from, address _to, uint256 _value) returns (bool success);         function approve(address _spender, uint256 _value) returns (bool success);      function allowance(address _owner, address _spender) constant returns (uint256 remaining);      event Transfer(address indexed _from, address indexed _to, uint256 _value);        event Approval(address indexed _owner, address indexed _spender, uint256 _value);  }\"  }]"

**Comment by suchitgupta60** [comment]
This is the contract that I am trying to compile. @kishorebhatia @samrit 
-------------------
[
  {
    "contractName": "ERC20Interface",
    "searchable": [
      "ERC20Interface"
    ],
    "source": "contract ERC20Interface {
 
     function totalSupply() constant returns (uint256 totalSupply);
   
      function balanceOf(address _owner) constant returns (uint256 balance);
   
      function transfer(address _to, uint256 _value) returns (bool success);
   
      function transferFrom(address _from, address _to, uint256 _value) returns (bool success);
   
      function approve(address _spender, uint256 _value) returns (bool success);
      function allowance(address _owner, address _spender) constant returns (uint256 remaining);
 
     event Transfer(address indexed _from, address indexed _to, uint256 _value);
  
      event Approval(address indexed _owner, address indexed _spender, uint256 _value);
  }"
  }
]

**Comment by samrit** [comment]
You need to implement the functions. This contract has no executable code. You will not be able to upload contracts with unimplemented functions.

**Comment by samrit** [comment]
See http://solidity.readthedocs.io/en/v0.4.8/contracts.html#abstract-contracts

**Comment by suchitgupta60** [comment]
I get the same error when I am compiling below contract. I am basically trying to test and create an ERC token.
@samrit 

`pragma solidity ^0.4.8; 
  contract ERC20Interface {
 
     function totalSupply() constant returns (uint256 totalSupply);
   
      function balanceOf(address _owner) constant returns (uint256 balance);
   
      function transfer(address _to, uint256 _value) returns (bool success);
   
      function transferFrom(address _from, address _to, uint256 _value) returns (bool success);
   
      function approve(address _spender, uint256 _value) returns (bool success);
      function allowance(address _owner, address _spender) constant returns (uint256 remaining);
 
     event Transfer(address indexed _from, address indexed _to, uint256 _value);
  
      event Approval(address indexed _owner, address indexed _spender, uint256 _value);
  }
   
  contract FixedSupplyToken is ERC20Interface {
      string public constant symbol = "XYX";
     string public constant name = "Sample Supply Token";
    uint8 public constant decimals = 18;
    uint256 _totalSupply = 1000000;
     
     address public owner;
  
     mapping(address => uint256) balances;
  
     mapping(address => mapping (address => uint256)) allowed;
  
     modifier onlyOwner() {
         if (msg.sender != owner) {
              throw;
         }
         _;
     }
     
     function FixedSupplyToken() {
         owner = msg.sender;
         balances[owner] = _totalSupply;
     }
  
     function totalSupply() constant returns (uint256 totalSupply) {
         totalSupply = _totalSupply;
     }
  
     function balanceOf(address _owner) constant returns (uint256 balance) {
         return balances[_owner];
    }
     function transfer(address _to, uint256 _amount) returns (bool success) {
         if (balances[msg.sender] >= _amount 
             && _amount > 0
             && balances[_to] + _amount > balances[_to]) {
             balances[msg.sender] -= _amount;
              balances[_to] += _amount;
             Transfer(msg.sender, _to, _amount);
             return true;
         } else {
              return false;
         }
     }
     function transferFrom(
         address _from,
         address _to,
         uint256 _amount
     ) returns (bool success) {
         if (balances[_from] >= _amount
             && allowed[_from][msg.sender] >= _amount
             && _amount > 0
             && balances[_to] + _amount > balances[_to]) {
             balances[_from] -= _amount;
             allowed[_from][msg.sender] -= _amount;
             balances[_to] += _amount;
             Transfer(_from, _to, _amount);
             return true;
         } else {
             return false;
         }
     }
  
 
     function approve(address _spender, uint256 _amount) returns (bool success) {
         allowed[msg.sender][_spender] = _amount;
         Approval(msg.sender, _spender, _amount);
         return true;
     }
  
     function allowance(address _owner, address _spender) constant returns (uint256 remaining) {
         return allowed[_owner][_spender];
     }
 }`
