### ISSUE TITLE
Error using SimpleStorage contract

### ISSUE THREAD

**Issue by ShaydeNofziger** [blockapps/strato-getting-started#18]
Using the Management Dashboard, I uploaded a `SimpleStego.sol` file containing the source code from the doc site.

The contract uploaded successfully, however both "set" and "get" are giving me troubles.

The "set" command appears to run successfully, with an empty array as a response. Attaching to the `strato_bloch_1` container shows the request succeeds with a `200`. When connecting to the DB with Postico, however, the storedData value does not get updated.

The "get" command errors, with `"Failed to parse response: "`. The running log on `strato_bloch_1` shows the `.../users/[username]/[user_address]/contract/[contract_address]/call` POST generating a `404: CouldNotFind "Failed to parse response: "` error.

Upon further investigation of the Postgres db using Postico, I found some weird values in the `abi` column of the `contract` table:

```json
{
    "address": null,
    "codeHash": "83d4f1a31f504bb7e3d67d489f6dc25cd1b383f86e71338c149edc4d30741b54",
    "name": "SimpleStorage",
    "xabi": {
        "funcs": {
            "set": {
                "args": {
                    "x": {
                        "signed": false,
                        "type": "Int",
                        "index": 0,
                        "bytes": 32
                    }
                },
                "vals": {}
            },
            "get": {
                "args": {},
                "vals": {
                    "#0": {
                        "signed": false,
                        "type": "Int",
                        "index": 0,
                        "bytes": 32
                    }
                }
            }
        },
        "types": {},
        "constr": {},
        "vars": {
            "storedData": {
                "atBytes": 0,
                "signed": false,
                "type": "Int",
                "bytes": 32,
                "public": null
            }
        }
    }
}
```

Notably, `address` is `null`, and `storedData`'s `public` value is `null`.

This issue occurs when running both the latest docker containers as well as with the `--stable` flag in the `.sh` call.

I also attempted to do this through API calls using Postman and Insomnia but had errors even getting the contract to compile.... I noticed the api documentation is lacking a bit, so perhaps I'm missing something or misinterpreting something.

Thanks for any help you can provide.

**Comment by ShaydeNofziger** [comment]
Host machine specs:

MacBook Pro running latest macOS.
Docker Version 17.06.1-ce-mac24 (stable)

Additionally, `docker ps` shows all containers are up and running

**Comment by samrit** [comment]
@ShaydeNofziger The database you are querying is a only used to store metadata and does not contain actual storage of the contract itself. It stores ABI information only and that is as expected. You can get this error if you try sending ether (in the value field) to a method that does not except ether. Try leaving the value field as 0 when calling the `get` and see if that helps.

**Comment by ShaydeNofziger** [comment]
Ahh, thank you! I'm still learning the blockchain and reading all the ethereum docs. I'll try that out and close this issue if that resolves it. Thank you!

Also, are Bloc / Strato api docs open source? I would love to help contribute to clear up some things that were confusing for me while getting started.

**Comment by samrit** [comment]
The docs are not open source. But please feel free to give me feedback and we'll improve them.
