### ISSUE TITLE
two containers: strato_bloch_1 and strato_nginx_1 are not starting. Keeps on restarting

### ISSUE THREAD

**Issue by sureshpalemoni** [blockapps/strato-getting-started#19]
As strato_nginx_1 depends on strato_bloch_1 , that is also not starting.

When I checked the logs for strato_bloch_1 container I see.

blockapps-bloc: libpq: failed (could not translate host name "postgres" to address: Temporary failure in name resolution.

**Comment by kjameslubin** [comment]
Hi Suresh, 
What system are you running on? Which version of docker?

**Comment by sureshpalemoni** [comment]
[root@openshift-master strato-getting-started]# docker -v
Docker version 1.12.6, build c4618fb/1.12.6

Our main intention was to deploy on openshift, however it seemed to be deployed locally. Could you please direct me to some document to deploy on openshift?
