### ISSUE TITLE
get total gas cost for all of trasaction

### ISSUE THREAD

**Issue by darkdudex** [blockapps/strato-getting-started#7]
is there an api call to get the sum total of the gas cost of all the transactions on the chain?

**Comment by jcrain** [comment]
Currently we don't expose an api for total gas. The `GET` transaction result route returns `gasPrice` and `gasLimit` but not total used.

**Comment by martyall** [comment]
While there is no route, you have access to the postgres docker container that keeps an auxiliary record of all the transactions that have ever been processed. You can connect directly to this and run your own queries.
